import React from 'react'
import styles from '../../../Avatar.module.scss';
import { LooksColor } from '@/src/interface';

const Stripes: React.FC<LooksColor> = ({ color, secondColor }) => {
    return (
        <svg version="1.1" viewBox='0 0 41 41' className={styles.colores} fill="currentColor" xmlns="http://www.w3.org/2000/svg" shapeRendering="crispEdges">
            <rect x="8" y="3" width="1" height="1" fill={color} />
            <rect x="9" y="3" width="1" height="1" fill={color} />
            <rect x="27" y="3" width="1" height="1" fill={color} />
            <rect x="7" y="4" width="1" height="1" fill={color} />
            <rect x="8" y="4" width="1" height="1" fill={color} />
            <rect x="9" y="4" width="1" height="1" fill={color} />
            <rect x="10" y="4" width="1" height="1" fill={color} />
            <rect x="25" y="4" width="1" height="1" fill={color} />
            <rect x="26" y="4" width="1" height="1" fill={color} />
            <rect x="27" y="4" width="1" height="1" fill={color} />
            <rect x="28" y="4" width="1" height="1" fill={color} />
            <rect x="7" y="5" width="1" height="1" fill={color} />
            <rect x="8" y="5" width="1" height="1" fill={color} />
            <rect x="9" y="5" width="1" height="1" fill={color} />
            <rect x="10" y="5" width="1" height="1" fill={color} />
            <rect x="11" y="5" width="1" height="1" fill={color} />
            <rect x="24" y="5" width="1" height="1" fill={color} />
            <rect x="25" y="5" width="1" height="1" fill={color} />
            <rect x="26" y="5" width="1" height="1" fill={color} />
            <rect x="27" y="5" width="1" height="1" fill={color} />
            <rect x="28" y="5" width="1" height="1" fill={color} />
            <rect x="6" y="6" width="1" height="1" fill={color} />
            <rect x="7" y="6" width="1" height="1" fill={color} />
            <rect x="8" y="6" width="1" height="1" fill={color} />
            <rect x="9" y="6" width="1" height="1" fill={color} />
            <rect x="10" y="6" width="1" height="1" fill={color} />
            <rect x="11" y="6" width="1" height="1" fill={color} />
            <rect x="12" y="6" width="1" height="1" fill={color} />
            <rect x="23" y="6" width="1" height="1" fill={color} />
            <rect x="24" y="6" width="1" height="1" fill={color} />
            <rect x="25" y="6" width="1" height="1" fill={color} />
            <rect x="26" y="6" width="1" height="1" fill={color} />
            <rect x="27" y="6" width="1" height="1" fill={color} />
            <rect x="28" y="6" width="1" height="1" fill={color} />
            <rect x="29" y="6" width="1" height="1" fill={color} />
            <rect x="6" y="7" width="1" height="1" fill={color} />
            <rect x="7" y="7" width="1" height="1" fill={color} />
            <rect x="8" y="7" width="1" height="1" fill={color} />
            <rect x="9" y="7" width="1" height="1" fill={color} />
            <rect x="10" y="7" width="1" height="1" fill={color} />
            <rect x="11" y="7" width="1" height="1" fill={color} />
            <rect x="12" y="7" width="1" height="1" fill={color} />
            <rect x="13" y="7" width="1" height="1" fill={color} />
            <rect x="24" y="7" width="1" height="1" fill={color} />
            <rect x="25" y="7" width="1" height="1" fill={color} />
            <rect x="26" y="7" width="1" height="1" fill={color} />
            <rect x="27" y="7" width="1" height="1" fill={color} />
            <rect x="28" y="7" width="1" height="1" fill={color} />
            <rect x="29" y="7" width="1" height="1" fill={color} />
            <rect x="5" y="8" width="1" height="1" fill={color} />
            <rect x="6" y="8" width="1" height="1" fill={color} />
            <rect x="7" y="8" width="1" height="1" fill={color} />
            <rect x="8" y="8" width="1" height="1" fill={color} />
            <rect x="9" y="8" width="1" height="1" fill={color} />
            <rect x="10" y="8" width="1" height="1" fill={color} />
            <rect x="11" y="8" width="1" height="1" fill={color} />
            <rect x="12" y="8" width="1" height="1" fill={color} />
            <rect x="16" y="8" width="1" height="1" fill={color} />
            <rect x="21" y="8" width="1" height="1" fill={color} />
            <rect x="22" y="8" width="1" height="1" fill={color} />
            <rect x="26" y="8" width="1" height="1" fill={color} />
            <rect x="27" y="8" width="1" height="1" fill={color} />
            <rect x="28" y="8" width="1" height="1" fill={color} />
            <rect x="29" y="8" width="1" height="1" fill={color} />
            <rect x="30" y="8" width="1" height="1" fill={color} />
            <rect x="5" y="9" width="1" height="1" fill={color} />
            <rect x="6" y="9" width="1" height="1" fill={color} />
            <rect x="7" y="9" width="1" height="1" fill={color} />
            <rect x="8" y="9" width="1" height="1" fill={color} />
            <rect x="9" y="9" width="1" height="1" fill={color} />
            <rect x="10" y="9" width="1" height="1" fill={color} />
            <rect x="11" y="9" width="1" height="1" fill={color} />
            <rect x="12" y="9" width="1" height="1" fill={color} />
            <rect x="13" y="9" width="1" height="1" fill={color} />
            <rect x="18" y="9" width="1" height="1" fill={color} />
            <rect x="19" y="9" width="1" height="1" fill={color} />
            <rect x="22" y="9" width="1" height="1" fill={color} />
            <rect x="23" y="9" width="1" height="1" fill={color} />
            <rect x="27" y="9" width="1" height="1" fill={color} />
            <rect x="28" y="9" width="1" height="1" fill={color} />
            <rect x="29" y="9" width="1" height="1" fill={color} />
            <rect x="30" y="9" width="1" height="1" fill={color} />
            <rect x="5" y="10" width="1" height="1" fill={color} />
            <rect x="6" y="10" width="1" height="1" fill={color} />
            <rect x="7" y="10" width="1" height="1" fill={color} />
            <rect x="8" y="10" width="1" height="1" fill={color} />
            <rect x="9" y="10" width="1" height="1" fill={color} />
            <rect x="10" y="10" width="1" height="1" fill={color} />
            <rect x="11" y="10" width="1" height="1" fill={color} />
            <rect x="12" y="10" width="1" height="1" fill={color} />
            <rect x="13" y="10" width="1" height="1" fill={color} />
            <rect x="19" y="10" width="1" height="1" fill={color} />
            <rect x="20" y="10" width="1" height="1" fill={color} />
            <rect x="24" y="10" width="1" height="1" fill={color} />
            <rect x="28" y="10" width="1" height="1" fill={color} />
            <rect x="29" y="10" width="1" height="1" fill={color} />
            <rect x="30" y="10" width="1" height="1" fill={color} />
            <rect x="5" y="11" width="1" height="1" fill={color} />
            <rect x="6" y="11" width="1" height="1" fill={color} />
            <rect x="7" y="11" width="1" height="1" fill={color} />
            <rect x="8" y="11" width="1" height="1" fill={color} />
            <rect x="9" y="11" width="1" height="1" fill={color} />
            <rect x="10" y="11" width="1" height="1" fill={color} />
            <rect x="11" y="11" width="1" height="1" fill={color} />
            <rect x="12" y="11" width="1" height="1" fill={color} />
            <rect x="13" y="11" width="1" height="1" fill={color} />
            <rect x="14" y="11" width="1" height="1" fill={color} />
            <rect x="15" y="11" width="1" height="1" fill={color} />
            <rect x="16" y="11" width="1" height="1" fill={color} />
            <rect x="20" y="11" width="1" height="1" fill={color} />
            <rect x="21" y="11" width="1" height="1" fill={color} />
            <rect x="25" y="11" width="1" height="1" fill={color} />
            <rect x="29" y="11" width="1" height="1" fill={color} />
            <rect x="30" y="11" width="1" height="1" fill={color} />
            <rect x="31" y="11" width="1" height="1" fill={color} />
            <rect x="6" y="12" width="1" height="1" fill={color} />
            <rect x="7" y="12" width="1" height="1" fill={color} />
            <rect x="8" y="12" width="1" height="1" fill={color} />
            <rect x="9" y="12" width="1" height="1" fill={color} />
            <rect x="10" y="12" width="1" height="1" fill={color} />
            <rect x="11" y="12" width="1" height="1" fill={color} />
            <rect x="12" y="12" width="1" height="1" fill={color} />
            <rect x="13" y="12" width="1" height="1" fill={color} />
            <rect x="14" y="12" width="1" height="1" fill={color} />
            <rect x="15" y="12" width="1" height="1" fill={color} />
            <rect x="16" y="12" width="1" height="1" fill={color} />
            <rect x="17" y="12" width="1" height="1" fill={color} />
            <rect x="21" y="12" width="1" height="1" fill={color} />
            <rect x="22" y="12" width="1" height="1" fill={color} />
            <rect x="26" y="12" width="1" height="1" fill={color} />
            <rect x="29" y="12" width="1" height="1" fill={color} />
            <rect x="30" y="12" width="1" height="1" fill={color} />
            <rect x="31" y="12" width="1" height="1" fill={color} />
            <rect x="6" y="13" width="1" height="1" fill={color} />
            <rect x="7" y="13" width="1" height="1" fill={color} />
            <rect x="8" y="13" width="1" height="1" fill={color} />
            <rect x="9" y="13" width="1" height="1" fill={color} />
            <rect x="10" y="13" width="1" height="1" fill={color} />
            <rect x="11" y="13" width="1" height="1" fill={color} />
            <rect x="12" y="13" width="1" height="1" fill={color} />
            <rect x="13" y="13" width="1" height="1" fill={color} />
            <rect x="14" y="13" width="1" height="1" fill={color} />
            <rect x="15" y="13" width="1" height="1" fill={color} />
            <rect x="16" y="13" width="1" height="1" fill={color} />
            <rect x="17" y="13" width="1" height="1" fill={color} />
            <rect x="18" y="13" width="1" height="1" fill={color} />
            <rect x="22" y="13" width="1" height="1" fill={color} />
            <rect x="23" y="13" width="1" height="1" fill={color} />
            <rect x="26" y="13" width="1" height="1" fill={color} />
            <rect x="27" y="13" width="1" height="1" fill={color} />
            <rect x="29" y="13" width="1" height="1" fill={color} />
            <rect x="30" y="13" width="1" height="1" fill={color} />
            <rect x="31" y="13" width="1" height="1" fill={color} />
            <rect x="32" y="13" width="1" height="1" fill={color} />
            <rect x="6" y="14" width="1" height="1" fill={color} />
            <rect x="7" y="14" width="1" height="1" fill={color} />
            <rect x="8" y="14" width="1" height="1" fill={color} />
            <rect x="9" y="14" width="1" height="1" fill={color} />
            <rect x="10" y="14" width="1" height="1" fill={color} />
            <rect x="11" y="14" width="1" height="1" fill={color} />
            <rect x="12" y="14" width="1" height="1" fill={color} />
            <rect x="13" y="14" width="1" height="1" fill={color} />
            <rect x="14" y="14" width="1" height="1" fill={color} />
            <rect x="15" y="14" width="1" height="1" fill={color} />
            <rect x="16" y="14" width="1" height="1" fill={color} />
            <rect x="17" y="14" width="1" height="1" fill={color} />
            <rect x="18" y="14" width="1" height="1" fill={color} />
            <rect x="19" y="14" width="1" height="1" fill={color} />
            <rect x="20" y="14" width="1" height="1" fill={color} />
            <rect x="22" y="14" width="1" height="1" fill={color} />
            <rect x="23" y="14" width="1" height="1" fill={color} />
            <rect x="26" y="14" width="1" height="1" fill={color} />
            <rect x="27" y="14" width="1" height="1" fill={color} />
            <rect x="29" y="14" width="1" height="1" fill={color} />
            <rect x="30" y="14" width="1" height="1" fill={color} />
            <rect x="31" y="14" width="1" height="1" fill={color} />
            <rect x="32" y="14" width="1" height="1" fill={color} />
            <rect x="5" y="15" width="1" height="1" fill={color} />
            <rect x="6" y="15" width="1" height="1" fill={color} />
            <rect x="7" y="15" width="1" height="1" fill={color} />
            <rect x="8" y="15" width="1" height="1" fill={color} />
            <rect x="9" y="15" width="1" height="1" fill={color} />
            <rect x="11" y="15" width="1" height="1" fill={color} />
            <rect x="12" y="15" width="1" height="1" fill={color} />
            <rect x="14" y="15" width="1" height="1" fill={color} />
            <rect x="16" y="15" width="1" height="1" fill={color} />
            <rect x="17" y="15" width="1" height="1" fill={color} />
            <rect x="18" y="15" width="1" height="1" fill={color} />
            <rect x="19" y="15" width="1" height="1" fill={color} />
            <rect x="20" y="15" width="1" height="1" fill={color} />
            <rect x="21" y="15" width="1" height="1" fill={color} />
            <rect x="22" y="15" width="1" height="1" fill={color} />
            <rect x="23" y="15" width="1" height="1" fill={color} />
            <rect x="24" y="15" width="1" height="1" fill={color} />
            <rect x="26" y="15" width="1" height="1" fill={color} />
            <rect x="27" y="15" width="1" height="1" fill={color} />
            <rect x="28" y="15" width="1" height="1" fill={color} />
            <rect x="29" y="15" width="1" height="1" fill={color} />
            <rect x="30" y="15" width="1" height="1" fill={color} />
            <rect x="32" y="15" width="1" height="1" fill={color} />
            <rect x="5" y="16" width="1" height="1" fill={color} />
            <rect x="6" y="16" width="1" height="1" fill={color} />
            <rect x="7" y="16" width="1" height="1" fill={color} />
            <rect x="8" y="16" width="1" height="1" fill={color} />
            <rect x="9" y="16" width="1" height="1" fill={color} />
            <rect x="10" y="16" width="1" height="1" fill={color} />
            <rect x="18" y="16" width="1" height="1" fill={color} />
            <rect x="19" y="16" width="1" height="1" fill={color} />
            <rect x="20" y="16" width="1" height="1" fill={color} />
            <rect x="21" y="16" width="1" height="1" fill={color} />
            <rect x="22" y="16" width="1" height="1" fill={color} />
            <rect x="23" y="16" width="1" height="1" fill={color} />
            <rect x="24" y="16" width="1" height="1" fill={color} />
            <rect x="26" y="16" width="1" height="1" fill={color} />
            <rect x="27" y="16" width="1" height="1" fill={color} />
            <rect x="28" y="16" width="1" height="1" fill={color} />
            <rect x="29" y="16" width="1" height="1" fill={color} />
            <rect x="5" y="17" width="1" height="1" fill={color} />
            <rect x="6" y="17" width="1" height="1" fill={color} />
            <rect x="7" y="17" width="1" height="1" fill={color} />
            <rect x="8" y="17" width="1" height="1" fill={color} />
            <rect x="9" y="17" width="1" height="1" fill={color} />
            <rect x="10" y="17" width="1" height="1" fill={color} />
            <rect x="14" y="17" width="1" height="1" fill="#dfdd97"/>
            <rect x="15" y="17" width="1" height="1" fill="#dfdd97"/>
            <rect x="16" y="17" width="1" height="1" fill="#1A1715" />
            <rect x="17" y="17" width="1" height="1" fill="#1A1715" />
            <rect x="19" y="17" width="1" height="1" fill={color} />
            <rect x="20" y="17" width="1" height="1" fill={color} />
            <rect x="21" y="17" width="1" height="1" fill={color} />
            <rect x="22" y="17" width="1" height="1" fill={color} />
            <rect x="23" y="17" width="1" height="1" fill={color} />
            <rect x="24" y="17" width="1" height="1" fill={color} />
            <rect x="25" y="17" width="1" height="1" fill={color} />
            <rect x="26" y="17" width="1" height="1" fill={color} />
            <rect x="27" y="17" width="1" height="1" fill={color} />
            <rect x="28" y="17" width="1" height="1" fill={color} />
            <rect x="30" y="17" width="1" height="1" fill="#1A1715" />
            <rect x="31" y="17" width="1" height="1" fill="#dfdd97"/>
            <rect x="5" y="18" width="1" height="1" fill={color} />
            <rect x="6" y="18" width="1" height="1" fill={color} />
            <rect x="7" y="18" width="1" height="1" fill={color} />
            <rect x="8" y="18" width="1" height="1" fill={color} />
            <rect x="9" y="18" width="1" height="1" fill={color} />
            <rect x="10" y="18" width="1" height="1" fill={color} />
            <rect x="11" y="18" width="1" height="1" fill={color} />
            <rect x="14" y="18" width="1" height="1" fill="#dfdd97"/>
            <rect x="15" y="18" width="1" height="1" fill="#1A1715" />
            <rect x="16" y="18" width="1" height="1" fill="#552C0F" />
            <rect x="17" y="18" width="1" height="1" fill="#552C0F" />
            <rect x="20" y="18" width="1" height="1" fill={color} />
            <rect x="21" y="18" width="1" height="1" fill={color} />
            <rect x="22" y="18" width="1" height="1" fill={color} />
            <rect x="23" y="18" width="1" height="1" fill={color} />
            <rect x="24" y="18" width="1" height="1" fill={color} />
            <rect x="25" y="18" width="1" height="1" fill={color} />
            <rect x="26" y="18" width="1" height="1" fill={color} />
            <rect x="27" y="18" width="1" height="1" fill={color} />
            <rect x="29" y="18" width="1" height="1" fill="#552C0F" />
            <rect x="30" y="18" width="1" height="1" fill="#552C0F" />
            <rect x="31" y="18" width="1" height="1" fill="#1A1715" />
            <rect x="33" y="18" width="1" height="1" fill={color} />
            <rect x="6" y="19" width="1" height="1" fill={color} />
            <rect x="7" y="19" width="1" height="1" fill={color} />
            <rect x="8" y="19" width="1" height="1" fill={color} />
            <rect x="9" y="19" width="1" height="1" fill={color} />
            <rect x="10" y="19" width="1" height="1" fill={color} />
            <rect x="11" y="19" width="1" height="1" fill={color} />
            <rect x="12" y="19" width="1" height="1" fill={color} />
            <rect x="13" y="19" width="1" height="1" fill={color} />
            <rect x="16" y="19" width="1" height="1" fill="#552C0F" />
            <rect x="18" y="19" width="1" height="1" fill={color} />
            <rect x="19" y="19" width="1" height="1" fill={color} />
            <rect x="20" y="19" width="1" height="1" fill={color} />
            <rect x="21" y="19" width="1" height="1" fill={color} />
            <rect x="22" y="19" width="1" height="1" fill={color} />
            <rect x="23" y="19" width="1" height="1" fill={color} />
            <rect x="24" y="19" width="1" height="1" fill={color} />
            <rect x="25" y="19" width="1" height="1" fill={color} />
            <rect x="26" y="19" width="1" height="1" fill={color} />
            <rect x="27" y="19" width="1" height="1" fill={color} />
            <rect x="28" y="19" width="1" height="1" fill={color} />
            <rect x="30" y="19" width="1" height="1" fill="#552C0F" />
            <rect x="32" y="19" width="1" height="1" fill={color} />
            <rect x="33" y="19" width="1" height="1" fill={color} />
            <rect x="7" y="20" width="1" height="1" fill={color} />
            <rect x="8" y="20" width="1" height="1" fill={color} />
            <rect x="9" y="20" width="1" height="1" fill={color} />
            <rect x="10" y="20" width="1" height="1" fill={color} />
            <rect x="11" y="20" width="1" height="1" fill={color} />
            <rect x="12" y="20" width="1" height="1" fill={color} />
            <rect x="13" y="20" width="1" height="1" fill={color} />
            <rect x="14" y="20" width="1" height="1" fill={color} />
            <rect x="15" y="20" width="1" height="1" fill={color} />
            <rect x="17" y="20" width="1" height="1" fill={color} />
            <rect x="18" y="20" width="1" height="1" fill={color} />
            <rect x="19" y="20" width="1" height="1" fill={color} />
            <rect x="20" y="20" width="1" height="1" fill={color} />
            <rect x="21" y="20" width="1" height="1" fill={color} />
            <rect x="22" y="20" width="1" height="1" fill={color} />
            <rect x="23" y="20" width="1" height="1" fill={color} />
            <rect x="24" y="20" width="1" height="1" fill={color} />
            <rect x="25" y="20" width="1" height="1" fill={color} />
            <rect x="26" y="20" width="1" height="1" fill={color} />
            <rect x="27" y="20" width="1" height="1" fill={color} />
            <rect x="28" y="20" width="1" height="1" fill={color} />
            <rect x="29" y="20" width="1" height="1" fill={color} />
            <rect x="31" y="20" width="1" height="1" fill={color} />
            <rect x="32" y="20" width="1" height="1" fill={color} />
            <rect x="13" y="21" width="1" height="1" fill={color} />
            <rect x="14" y="21" width="1" height="1" fill={color} />
            <rect x="15" y="21" width="1" height="1" fill={color} />
            <rect x="16" y="21" width="1" height="1" fill={color} />
            <rect x="17" y="21" width="1" height="1" fill={color} />
            <rect x="18" y="21" width="1" height="1" fill={color} />
            <rect x="19" y="21" width="1" height="1" fill={color} />
            <rect x="28" y="21" width="1" height="1" fill={color} />
            <rect x="29" y="21" width="1" height="1" fill={color} />
            <rect x="30" y="21" width="1" height="1" fill={color} />
            <rect x="31" y="21" width="1" height="1" fill={color} />
            <rect x="4" y="22" width="1" height="1" fill={color} />
            <rect x="5" y="22" width="1" height="1" fill={color} />
            <rect x="6" y="22" width="1" height="1" fill={color} />
            <rect x="11" y="22" width="1" height="1" fill={color} />
            <rect x="12" y="22" width="1" height="1" fill={color} />
            <rect x="13" y="22" width="1" height="1" fill={color} />
            <rect x="14" y="22" width="1" height="1" fill={color} />
            <rect x="15" y="22" width="1" height="1" fill={color} />
            <rect x="30" y="22" width="1" height="1" fill={color} />
            <rect x="31" y="22" width="1" height="1" fill={color} />
            <rect x="32" y="22" width="1" height="1" fill={color} />
            <rect x="33" y="22" width="1" height="1" fill={color} />
            <rect x="6" y="23" width="1" height="1" fill={color} />
            <rect x="7" y="23" width="1" height="1" fill={color} />
            <rect x="8" y="23" width="1" height="1" fill={color} />
            <rect x="9" y="23" width="1" height="1" fill={color} />
            <rect x="10" y="23" width="1" height="1" fill={color} />
            <rect x="11" y="23" width="1" height="1" fill={color} />
            <rect x="12" y="23" width="1" height="1" fill={color} />
            <rect x="13" y="23" width="1" height="1" fill={color} />
            <rect x="31" y="23" width="1" height="1" fill={color} />
            <rect x="32" y="23" width="1" height="1" fill={color} />
            <rect x="10" y="24" width="1" height="1" fill={color} />
            <rect x="11" y="24" width="1" height="1" fill={color} />
            <rect x="12" y="24" width="1" height="1" fill={color} />
            <rect x="32" y="24" width="1" height="1" fill={color} />
            <rect x="5" y="25" width="1" height="1" fill={color} />
            <rect x="8" y="25" width="1" height="1" fill={color} />
            <rect x="9" y="25" width="1" height="1" fill={color} />
            <rect x="10" y="25" width="1" height="1" fill={color} />
            <rect x="11" y="25" width="1" height="1" fill={color} />
            <rect x="6" y="26" width="1" height="1" fill={color} />
            <rect x="7" y="26" width="1" height="1" fill={color} />
            <rect x="8" y="26" width="1" height="1" fill={color} />
            <rect x="9" y="26" width="1" height="1" fill={color} />
            <rect x="10" y="26" width="1" height="1" fill={color} />
            <rect x="11" y="26" width="1" height="1" fill={color} />
            <rect x="33" y="26" width="1" height="1" fill={color} />
            <rect x="10" y="27" width="1" height="1" fill={color} />
            <rect x="11" y="27" width="1" height="1" fill={color} />
            <rect x="32" y="27" width="1" height="1" fill={color} />
            <rect x="8" y="28" width="1" height="1" fill={color} />
            <rect x="9" y="28" width="1" height="1" fill={color} />
            <rect x="10" y="28" width="1" height="1" fill={color} />
            <rect x="11" y="28" width="1" height="1" fill={color} />
            <rect x="8" y="29" width="1" height="1" fill={color} />
            <rect x="9" y="29" width="1" height="1" fill={color} />
            <rect x="10" y="29" width="1" height="1" fill={color} />
            <rect x="11" y="29" width="1" height="1" fill={color} />
            <rect x="31" y="29" width="1" height="1" fill={color} />
            <rect x="9" y="30" width="1" height="1" fill={color} />
            <rect x="10" y="30" width="1" height="1" fill={color} />
            <rect x="11" y="30" width="1" height="1" fill={color} />
            <rect x="12" y="30" width="1" height="1" fill={color} />
            <rect x="30" y="30" width="1" height="1" fill={color} />
            <rect x="11" y="31" width="1" height="1" fill={color} />
            <rect x="12" y="31" width="1" height="1" fill={color} />
            <rect x="13" y="31" width="1" height="1" fill={color} />
            <rect x="14" y="31" width="1" height="1" fill={color} />
            <rect x="12" y="32" width="1" height="1" fill={color} />
            <rect x="13" y="32" width="1" height="1" fill={color} />
            <rect x="14" y="32" width="1" height="1" fill={color} />
            <rect x="15" y="32" width="1" height="1" fill={color} />
            <rect x="14" y="36" width="1" height="1" fill={color} />
            <rect x="15" y="36" width="1" height="1" fill={color} />
            <rect x="18" y="36" width="1" height="1" fill={color} />
            <rect x="14" y="37" width="1" height="1" fill={color} />
            <rect x="15" y="37" width="1" height="1" fill={color} />
            <rect x="16" y="37" width="1" height="1" fill={color} />
            <rect x="17" y="37" width="1" height="1" fill={color} />
            <rect x="18" y="37" width="1" height="1" fill={color} />
            <rect x="19" y="37" width="1" height="1" fill={color} />
            <rect x="15" y="38" width="1" height="1" fill={color} />
            <rect x="16" y="38" width="1" height="1" fill={color} />
            <rect x="17" y="38" width="1" height="1" fill={color} />
            <rect x="19" y="38" width="1" height="1" fill={color} />
            <rect x="20" y="38" width="1" height="1" fill={color} />
            <rect x="21" y="38" width="1" height="1" fill={color} />
            <rect x="22" y="38" width="1" height="1" fill={color} />
            <rect x="16" y="39" width="1" height="1" fill={color} />
            <rect x="17" y="39" width="1" height="1" fill={color} />
            <rect x="18" y="39" width="1" height="1" fill={color} />
            <rect x="23" y="39" width="1" height="1" fill={color} />
            <rect x="24" y="39" width="1" height="1" fill={color} />
            <rect x="18" y="40" width="1" height="1" fill={color} />
            <rect x="19" y="40" width="1" height="1" fill={color} />
            <rect x="25" y="40" width="1" height="1" fill={color} />
        </svg>
    )
}

export default Stripes