import React from 'react'
import styles from '../../../Avatar.module.scss';
import {colors} from "@/src/interface/avatar";

const BraidsM: React.FC<colors> = ({ colorPrincipal, colorSecond }) => {
    return (
        <svg version="1.1" viewBox='0 0 41 41' className={styles.colores} fill="currentColor" xmlns="http://www.w3.org/2000/svg" shapeRendering="crispEdges">
            <rect x="7" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="16" y="0" width="1" height="1" fill={colorSecond} />
            <rect x="17" y="0" width="1" height="1" fill={colorSecond} />
            <rect x="18" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="19" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="20" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="23" y="0" width="1" height="1" fill={colorPrincipal} />
            <rect x="11" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="12" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="13" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="14" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="15" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="18" y="1" width="1" height="1" fill={colorSecond} />
            <rect x="19" y="1" width="1" height="1" fill={colorSecond} />
            <rect x="20" y="1" width="1" height="1" fill={colorSecond} />
            <rect x="21" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="22" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="24" y="1" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="12" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="13" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="14" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="15" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="16" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="17" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="21" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="22" y="2" width="1" height="1" fill={colorSecond} />
            <rect x="23" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="25" y="2" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="3" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="7" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="16" y="3" width="1" height="1" fill={colorSecond} />
            <rect x="17" y="3" width="1" height="1" fill={colorSecond} />
            <rect x="18" y="3" width="1" height="1" fill={colorSecond} />
            <rect x="19" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="20" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="23" y="3" width="1" height="1" fill={colorSecond} />
            <rect x="24" y="3" width="1" height="1" fill={colorPrincipal} />
            <rect x="26" y="3" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="7" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="12" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="13" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="14" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="15" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="19" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="20" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="21" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="23" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="24" y="4" width="1" height="1" fill={colorPrincipal} />
            <rect x="25" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="27" y="4" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="5" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="5" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="5" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="13" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="14" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="15" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="16" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="17" y="5" width="1" height="1" fill={colorPrincipal} />
            <rect x="18" y="5" width="1" height="1" fill={colorPrincipal} />
            <rect x="21" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="22" y="5" width="1" height="1" fill={colorPrincipal} />
            <rect x="24" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="25" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="27" y="5" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="6" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="6" width="1" height="1" fill={colorPrincipal} />
            <rect x="12" y="6" width="1" height="1" fill={colorPrincipal} />
            <rect x="13" y="6" width="1" height="1" fill={colorPrincipal} />
            <rect x="17" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="18" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="19" y="6" width="1" height="1" fill={colorPrincipal} />
            <rect x="21" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="22" y="6" width="1" height="1" fill={colorPrincipal} />
            <rect x="24" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="28" y="6" width="1" height="1" fill={colorSecond} />
            <rect x="1" y="7" width="1" height="1" fill={colorPrincipal} />
            <rect x="2" y="7" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="7" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="7" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="7" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="7" width="1" height="1" fill={colorSecond} />
            <rect x="12" y="7" width="1" height="1" fill={colorSecond} />
            <rect x="13" y="7" width="1" height="1" fill={colorSecond} />
            <rect x="14" y="7" width="1" height="1" fill={colorPrincipal} />
            <rect x="15" y="7" width="1" height="1" fill={colorPrincipal} />
            <rect x="28" y="7" width="1" height="1" fill={colorSecond} />
            <rect x="1" y="8" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="8" width="1" height="1" fill={colorPrincipal} />
            <rect x="7" y="8" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="8" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="8" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="8" width="1" height="1" fill={colorPrincipal} />
            <rect x="14" y="8" width="1" height="1" fill={colorSecond} />
            <rect x="15" y="8" width="1" height="1" fill={colorSecond} />
            <rect x="0" y="9" width="1" height="1" fill={colorPrincipal} />
            <rect x="2" y="9" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="9" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="9" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="9" width="1" height="1" fill={colorPrincipal} />
            <rect x="12" y="9" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="10" width="1" height="1" fill={colorPrincipal} />
            <rect x="2" y="10" width="1" height="1" fill={colorPrincipal} />
            <rect x="11" y="10" width="1" height="1" fill={colorSecond} />
            <rect x="12" y="10" width="1" height="1" fill={colorSecond} />
            <rect x="0" y="11" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="11" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="11" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="11" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="11" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="11" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="11" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="11" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="12" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="12" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="12" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="12" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="12" width="1" height="1" fill={colorPrincipal} />
            <rect x="0" y="13" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="13" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="13" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="13" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="13" width="1" height="1" fill={colorSecond} />
            <rect x="1" y="14" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="14" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="14" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="14" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="14" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="14" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="14" width="1" height="1" fill={colorPrincipal} />
            <rect x="0" y="15" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="15" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="15" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="15" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="15" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="15" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="15" width="1" height="1" fill={colorPrincipal} />
            <rect x="0" y="16" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="16" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="16" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="16" width="1" height="1" fill={colorSecond} />
            <rect x="13" y="16" width="1" height="1" fill={colorPrincipal} />
            <rect x="26" y="16" width="1" height="1" fill={colorPrincipal} />
            <rect x="0" y="17" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="17" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="17" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="17" width="1" height="1" fill={colorSecond} />
            <rect x="0" y="18" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="18" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="18" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="18" width="1" height="1" fill={colorSecond} />
            <rect x="0" y="19" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="19" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="19" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="20" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="20" width="1" height="1" fill={colorPrincipal} />
            <rect x="1" y="21" width="1" height="1" fill={colorPrincipal} />
            <rect x="2" y="21" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="21" width="1" height="1" fill={colorPrincipal} />
            <rect x="2" y="22" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="22" width="1" height="1" fill={colorPrincipal} />
            <rect x="2" y="23" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="23" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="23" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="23" width="1" height="1" fill={colorSecond} />
            <rect x="2" y="24" width="1" height="1" fill={colorPrincipal} />
            <rect x="3" y="24" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="24" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="24" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="25" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="25" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="25" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="25" width="1" height="1" fill={colorSecond} />
            <rect x="3" y="26" width="1" height="1" fill={colorPrincipal} />
            <rect x="4" y="26" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="26" width="1" height="1" fill={colorPrincipal} />
            <rect x="7" y="26" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="27" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="27" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="27" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="27" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="28" width="1" height="1" fill={colorPrincipal} />
            <rect x="5" y="28" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="28" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="28" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="29" width="1" height="1" fill={colorPrincipal} />
            <rect x="6" y="29" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="29" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="29" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="30" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="30" width="1" height="1" fill={colorPrincipal} />
            <rect x="7" y="30" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="30" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="30" width="1" height="1" fill={colorSecond} />
            <rect x="4" y="31" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="31" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="31" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="31" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="31" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="31" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="32" width="1" height="1" fill={colorSecond} />
            <rect x="7" y="32" width="1" height="1" fill={colorPrincipal} />
            <rect x="8" y="32" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="32" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="32" width="1" height="1" fill={colorSecond} />
            <rect x="5" y="33" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="33" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="33" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="33" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="33" width="1" height="1" fill={colorPrincipal} />
            <rect x="11" y="33" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="34" width="1" height="1" fill={colorSecond} />
            <rect x="8" y="34" width="1" height="1" fill={colorPrincipal} />
            <rect x="9" y="34" width="1" height="1" fill={colorSecond} />
            <rect x="10" y="34" width="1" height="1" fill={colorPrincipal} />
            <rect x="11" y="34" width="1" height="1" fill={colorSecond} />
            <rect x="12" y="34" width="1" height="1" fill={colorSecond} />
            <rect x="6" y="35" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="35" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="35" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="35" width="1" height="1" fill={colorPrincipal} />
            <rect x="12" y="35" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="36" width="1" height="1" fill={colorPrincipal} />
            <rect x="10" y="36" width="1" height="1" fill={colorSecond} />
            <rect x="11" y="36" width="1" height="1" fill={colorPrincipal} />
            <rect x="12" y="36" width="1" height="1" fill={colorSecond} />
            <rect x="9" y="37" width="1" height="1" fill={colorPrincipal} />
            <rect x="12" y="37" width="1" height="1" fill={colorSecond} />
        </svg>
    )
}

export default BraidsM