import React from 'react'
import styles from '../../../Avatar.module.scss';
import { LooksColor } from '@/src/interface';

const CurlersM
: React.FC<LooksColor> = ({ color, secondColor }) => {
    return (
        <svg version="1.1" viewBox='0 0 41 41' className={styles.colores} fill="currentColor" xmlns="http://www.w3.org/2000/svg" shapeRendering="crispEdges">
            <rect x="6" y="0" width="1" height="1" fill={color} />
            <rect x="8" y="0" width="1" height="1" fill={secondColor} />
            <rect x="9" y="0" width="1" height="1" fill={color} />
            <rect x="10" y="0" width="1" height="1" fill={color} />
            <rect x="11" y="0" width="1" height="1" fill={color} />
            <rect x="13" y="0" width="1" height="1" fill={color} />
            <rect x="14" y="0" width="1" height="1" fill={color} />
            <rect x="15" y="0" width="1" height="1" fill={secondColor} />
            <rect x="16" y="0" width="1" height="1" fill={secondColor} />
            <rect x="17" y="0" width="1" height="1" fill={secondColor} />
            <rect x="18" y="0" width="1" height="1" fill={color} />
            <rect x="19" y="0" width="1" height="1" fill={color} />
            <rect x="20" y="0" width="1" height="1" fill={color} />
            <rect x="21" y="0" width="1" height="1" fill={secondColor} />
            <rect x="22" y="0" width="1" height="1" fill={secondColor} />
            <rect x="24" y="0" width="1" height="1" fill={secondColor} />
            <rect x="25" y="0" width="1" height="1" fill={secondColor} />
            <rect x="26" y="0" width="1" height="1" fill={secondColor} />
            <rect x="5" y="1" width="1" height="1" fill={color} />
            <rect x="6" y="1" width="1" height="1" fill={color} />
            <rect x="12" y="1" width="1" height="1" fill={color} />
            <rect x="13" y="1" width="1" height="1" fill={color} />
            <rect x="15" y="1" width="1" height="1" fill={color} />
            <rect x="16" y="1" width="1" height="1" fill={color} />
            <rect x="17" y="1" width="1" height="1" fill={color} />
            <rect x="18" y="1" width="1" height="1" fill={color} />
            <rect x="19" y="1" width="1" height="1" fill={secondColor} />
            <rect x="20" y="1" width="1" height="1" fill={secondColor} />
            <rect x="21" y="1" width="1" height="1" fill={secondColor} />
            <rect x="23" y="1" width="1" height="1" fill={color} />
            <rect x="24" y="1" width="1" height="1" fill={color} />
            <rect x="25" y="1" width="1" height="1" fill={secondColor} />
            <rect x="26" y="1" width="1" height="1" fill={secondColor} />
            <rect x="27" y="1" width="1" height="1" fill={secondColor} />
            <rect x="4" y="2" width="1" height="1" fill={color} />
            <rect x="5" y="2" width="1" height="1" fill={color} />
            <rect x="6" y="2" width="1" height="1" fill={color} />
            <rect x="7" y="2" width="1" height="1" fill={color} />
            <rect x="8" y="2" width="1" height="1" fill={color} />
            <rect x="9" y="2" width="1" height="1" fill={color} />
            <rect x="10" y="2" width="1" height="1" fill={color} />
            <rect x="11" y="2" width="1" height="1" fill={color} />
            <rect x="12" y="2" width="1" height="1" fill={color} />
            <rect x="14" y="2" width="1" height="1" fill={secondColor} />
            <rect x="15" y="2" width="1" height="1" fill={color} />
            <rect x="19" y="2" width="1" height="1" fill={color} />
            <rect x="20" y="2" width="1" height="1" fill={color} />
            <rect x="21" y="2" width="1" height="1" fill={secondColor} />
            <rect x="23" y="2" width="1" height="1" fill={secondColor} />
            <rect x="24" y="2" width="1" height="1" fill={color} />
            <rect x="25" y="2" width="1" height="1" fill={secondColor} />
            <rect x="26" y="2" width="1" height="1" fill={secondColor} />
            <rect x="27" y="2" width="1" height="1" fill={secondColor} />
            <rect x="2" y="3" width="1" height="1" fill={color} />
            <rect x="3" y="3" width="1" height="1" fill={color} />
            <rect x="4" y="3" width="1" height="1" fill={color} />
            <rect x="5" y="3" width="1" height="1" fill={color} />
            <rect x="6" y="3" width="1" height="1" fill={color} />
            <rect x="9" y="3" width="1" height="1" fill={color} />
            <rect x="10" y="3" width="1" height="1" fill={color} />
            <rect x="11" y="3" width="1" height="1" fill={color} />
            <rect x="13" y="3" width="1" height="1" fill={secondColor} />
            <rect x="14" y="3" width="1" height="1" fill={color} />
            <rect x="15" y="3" width="1" height="1" fill={color} />
            <rect x="17" y="3" width="1" height="1" fill={secondColor} />
            <rect x="20" y="3" width="1" height="1" fill={color} />
            <rect x="21" y="3" width="1" height="1" fill={color} />
            <rect x="22" y="3" width="1" height="1" fill={color} />
            <rect x="26" y="3" width="1" height="1" fill={color} />
            <rect x="27" y="3" width="1" height="1" fill={secondColor} />
            <rect x="28" y="3" width="1" height="1" fill={secondColor} />
            <rect x="1" y="4" width="1" height="1" fill={color} />
            <rect x="2" y="4" width="1" height="1" fill={color} />
            <rect x="3" y="4" width="1" height="1" fill={color} />
            <rect x="4" y="4" width="1" height="1" fill={color} />
            <rect x="5" y="4" width="1" height="1" fill={color} />
            <rect x="8" y="4" width="1" height="1" fill={color} />
            <rect x="9" y="4" width="1" height="1" fill={color} />
            <rect x="10" y="4" width="1" height="1" fill={color} />
            <rect x="11" y="4" width="1" height="1" fill={color} />
            <rect x="13" y="4" width="1" height="1" fill={secondColor} />
            <rect x="14" y="4" width="1" height="1" fill={color} />
            <rect x="15" y="4" width="1" height="1" fill={color} />
            <rect x="16" y="4" width="1" height="1" fill={secondColor} />
            <rect x="17" y="4" width="1" height="1" fill={color} />
            <rect x="18" y="4" width="1" height="1" fill={color} />
            <rect x="19" y="4" width="1" height="1" fill={secondColor} />
            <rect x="21" y="4" width="1" height="1" fill={color} />
            <rect x="22" y="4" width="1" height="1" fill={color} />
            <rect x="23" y="4" width="1" height="1" fill={color} />
            <rect x="24" y="4" width="1" height="1" fill={color} />
            <rect x="25" y="4" width="1" height="1" fill={secondColor} />
            <rect x="27" y="4" width="1" height="1" fill={color} />
            <rect x="28" y="4" width="1" height="1" fill={secondColor} />
            <rect x="29" y="4" width="1" height="1" fill={secondColor} />
            <rect x="0" y="5" width="1" height="1" fill={color} />
            <rect x="1" y="5" width="1" height="1" fill={color} />
            <rect x="2" y="5" width="1" height="1" fill={color} />
            <rect x="3" y="5" width="1" height="1" fill={color} />
            <rect x="6" y="5" width="1" height="1" fill={color} />
            <rect x="7" y="5" width="1" height="1" fill={color} />
            <rect x="8" y="5" width="1" height="1" fill={color} />
            <rect x="9" y="5" width="1" height="1" fill={color} />
            <rect x="10" y="5" width="1" height="1" fill={color} />
            <rect x="11" y="5" width="1" height="1" fill={color} />
            <rect x="12" y="5" width="1" height="1" fill={color} />
            <rect x="14" y="5" width="1" height="1" fill={secondColor} />
            <rect x="15" y="5" width="1" height="1" fill={color} />
            <rect x="16" y="5" width="1" height="1" fill={color} />
            <rect x="17" y="5" width="1" height="1" fill={color} />
            <rect x="18" y="5" width="1" height="1" fill={secondColor} />
            <rect x="21" y="5" width="1" height="1" fill={color} />
            <rect x="22" y="5" width="1" height="1" fill={color} />
            <rect x="23" y="5" width="1" height="1" fill={color} />
            <rect x="24" y="5" width="1" height="1" fill={color} />
            <rect x="26" y="5" width="1" height="1" fill={color} />
            <rect x="27" y="5" width="1" height="1" fill={secondColor} />
            <rect x="30" y="5" width="1" height="1" fill={secondColor} />
            <rect x="1" y="6" width="1" height="1" fill={color} />
            <rect x="2" y="6" width="1" height="1" fill={color} />
            <rect x="3" y="6" width="1" height="1" fill={color} />
            <rect x="5" y="6" width="1" height="1" fill={color} />
            <rect x="6" y="6" width="1" height="1" fill={color} />
            <rect x="7" y="6" width="1" height="1" fill={color} />
            <rect x="11" y="6" width="1" height="1" fill={color} />
            <rect x="12" y="6" width="1" height="1" fill={color} />
            <rect x="13" y="6" width="1" height="1" fill={color} />
            <rect x="20" y="6" width="1" height="1" fill={color} />
            <rect x="21" y="6" width="1" height="1" fill={color} />
            <rect x="22" y="6" width="1" height="1" fill={color} />
            <rect x="23" y="6" width="1" height="1" fill={color} />
            <rect x="24" y="6" width="1" height="1" fill={color} />
            <rect x="25" y="6" width="1" height="1" fill={color} />
            <rect x="27" y="6" width="1" height="1" fill={color} />
            <rect x="28" y="6" width="1" height="1" fill={secondColor} />
            <rect x="30" y="6" width="1" height="1" fill={secondColor} />
            <rect x="0" y="7" width="1" height="1" fill={color} />
            <rect x="3" y="7" width="1" height="1" fill={color} />
            <rect x="5" y="7" width="1" height="1" fill={color} />
            <rect x="6" y="7" width="1" height="1" fill={color} />
            <rect x="7" y="7" width="1" height="1" fill={secondColor} />
            <rect x="9" y="7" width="1" height="1" fill={secondColor} />
            <rect x="12" y="7" width="1" height="1" fill={secondColor} />
            <rect x="13" y="7" width="1" height="1" fill={color} />
            <rect x="14" y="7" width="1" height="1" fill={color} />
            <rect x="15" y="7" width="1" height="1" fill={color} />
            <rect x="16" y="7" width="1" height="1" fill={color} />
            <rect x="17" y="7" width="1" height="1" fill={color} />
            <rect x="25" y="7" width="1" height="1" fill={color} />
            <rect x="26" y="7" width="1" height="1" fill={color} />
            <rect x="29" y="7" width="1" height="1" fill={secondColor} />
            <rect x="30" y="7" width="1" height="1" fill={secondColor} />
            <rect x="0" y="8" width="1" height="1" fill={color} />
            <rect x="1" y="8" width="1" height="1" fill={secondColor} />
            <rect x="3" y="8" width="1" height="1" fill={color} />
            <rect x="6" y="8" width="1" height="1" fill={color} />
            <rect x="7" y="8" width="1" height="1" fill={color} />
            <rect x="8" y="8" width="1" height="1" fill={secondColor} />
            <rect x="9" y="8" width="1" height="1" fill={color} />
            <rect x="12" y="8" width="1" height="1" fill={secondColor} />
            <rect x="13" y="8" width="1" height="1" fill={color} />
            <rect x="14" y="8" width="1" height="1" fill={color} />
            <rect x="15" y="8" width="1" height="1" fill={color} />
            <rect x="26" y="8" width="1" height="1" fill={color} />
            <rect x="27" y="8" width="1" height="1" fill={color} />
            <rect x="28" y="8" width="1" height="1" fill={secondColor} />
            <rect x="29" y="8" width="1" height="1" fill={secondColor} />
            <rect x="30" y="8" width="1" height="1" fill={secondColor} />
            <rect x="31" y="8" width="1" height="1" fill={secondColor} />
            <rect x="0" y="9" width="1" height="1" fill={secondColor} />
            <rect x="2" y="9" width="1" height="1" fill={color} />
            <rect x="3" y="9" width="1" height="1" fill={color} />
            <rect x="4" y="9" width="1" height="1" fill={secondColor} />
            <rect x="10" y="9" width="1" height="1" fill={secondColor} />
            <rect x="11" y="9" width="1" height="1" fill={secondColor} />
            <rect x="12" y="9" width="1" height="1" fill={color} />
            <rect x="13" y="9" width="1" height="1" fill={color} />
            <rect x="14" y="9" width="1" height="1" fill={color} />
            <rect x="27" y="9" width="1" height="1" fill={color} />
            <rect x="28" y="9" width="1" height="1" fill={color} />
            <rect x="29" y="9" width="1" height="1" fill={secondColor} />
            <rect x="30" y="9" width="1" height="1" fill={secondColor} />
            <rect x="31" y="9" width="1" height="1" fill={secondColor} />
            <rect x="0" y="10" width="1" height="1" fill={secondColor} />
            <rect x="2" y="10" width="1" height="1" fill={color} />
            <rect x="3" y="10" width="1" height="1" fill={color} />
            <rect x="4" y="10" width="1" height="1" fill={color} />
            <rect x="5" y="10" width="1" height="1" fill={secondColor} />
            <rect x="6" y="10" width="1" height="1" fill={secondColor} />
            <rect x="7" y="10" width="1" height="1" fill={secondColor} />
            <rect x="8" y="10" width="1" height="1" fill={secondColor} />
            <rect x="9" y="10" width="1" height="1" fill={secondColor} />
            <rect x="10" y="10" width="1" height="1" fill={color} />
            <rect x="11" y="10" width="1" height="1" fill={color} />
            <rect x="12" y="10" width="1" height="1" fill={color} />
            <rect x="13" y="10" width="1" height="1" fill={color} />
            <rect x="14" y="10" width="1" height="1" fill={color} />
            <rect x="15" y="10" width="1" height="1" fill={color} />
            <rect x="28" y="10" width="1" height="1" fill={color} />
            <rect x="29" y="10" width="1" height="1" fill={secondColor} />
            <rect x="30" y="10" width="1" height="1" fill={secondColor} />
            <rect x="31" y="10" width="1" height="1" fill={secondColor} />
            <rect x="1" y="11" width="1" height="1" fill={color} />
            <rect x="2" y="11" width="1" height="1" fill={color} />
            <rect x="5" y="11" width="1" height="1" fill={color} />
            <rect x="6" y="11" width="1" height="1" fill={color} />
            <rect x="7" y="11" width="1" height="1" fill={color} />
            <rect x="8" y="11" width="1" height="1" fill={color} />
            <rect x="9" y="11" width="1" height="1" fill={color} />
            <rect x="11" y="11" width="1" height="1" fill={secondColor} />
            <rect x="12" y="11" width="1" height="1" fill={color} />
            <rect x="13" y="11" width="1" height="1" fill={color} />
            <rect x="15" y="11" width="1" height="1" fill={color} />
            <rect x="29" y="11" width="1" height="1" fill={secondColor} />
            <rect x="30" y="11" width="1" height="1" fill={secondColor} />
            <rect x="31" y="11" width="1" height="1" fill={secondColor} />
            <rect x="0" y="12" width="1" height="1" fill={color} />
            <rect x="1" y="12" width="1" height="1" fill={color} />
            <rect x="3" y="12" width="1" height="1" fill={secondColor} />
            <rect x="4" y="12" width="1" height="1" fill={color} />
            <rect x="5" y="12" width="1" height="1" fill={color} />
            <rect x="6" y="12" width="1" height="1" fill={color} />
            <rect x="7" y="12" width="1" height="1" fill={color} />
            <rect x="8" y="12" width="1" height="1" fill={color} />
            <rect x="9" y="12" width="1" height="1" fill={color} />
            <rect x="11" y="12" width="1" height="1" fill={secondColor} />
            <rect x="12" y="12" width="1" height="1" fill={secondColor} />
            <rect x="14" y="12" width="1" height="1" fill={color} />
            <rect x="15" y="12" width="1" height="1" fill={secondColor} />
            <rect x="31" y="12" width="1" height="1" fill={secondColor} />
            <rect x="0" y="13" width="1" height="1" fill={color} />
            <rect x="2" y="13" width="1" height="1" fill={secondColor} />
            <rect x="3" y="13" width="1" height="1" fill={color} />
            <rect x="4" y="13" width="1" height="1" fill={color} />
            <rect x="5" y="13" width="1" height="1" fill={color} />
            <rect x="8" y="13" width="1" height="1" fill={secondColor} />
            <rect x="9" y="13" width="1" height="1" fill={color} />
            <rect x="10" y="13" width="1" height="1" fill={color} />
            <rect x="13" y="13" width="1" height="1" fill={color} />
            <rect x="14" y="13" width="1" height="1" fill={secondColor} />
            <rect x="31" y="13" width="1" height="1" fill={secondColor} />
            <rect x="0" y="14" width="1" height="1" fill={color} />
            <rect x="2" y="14" width="1" height="1" fill={secondColor} />
            <rect x="3" y="14" width="1" height="1" fill={color} />
            <rect x="4" y="14" width="1" height="1" fill={color} />
            <rect x="6" y="14" width="1" height="1" fill={secondColor} />
            <rect x="8" y="14" width="1" height="1" fill={secondColor} />
            <rect x="9" y="14" width="1" height="1" fill={color} />
            <rect x="10" y="14" width="1" height="1" fill={color} />
            <rect x="11" y="14" width="1" height="1" fill={secondColor} />
            <rect x="12" y="14" width="1" height="1" fill={secondColor} />
            <rect x="13" y="14" width="1" height="1" fill={secondColor} />
            <rect x="31" y="14" width="1" height="1" fill={secondColor} />
            <rect x="32" y="14" width="1" height="1" fill={secondColor} />
            <rect x="0" y="15" width="1" height="1" fill={color} />
            <rect x="3" y="15" width="1" height="1" fill={secondColor} />
            <rect x="4" y="15" width="1" height="1" fill={secondColor} />
            <rect x="5" y="15" width="1" height="1" fill={secondColor} />
            <rect x="7" y="15" width="1" height="1" fill={secondColor} />
            <rect x="8" y="15" width="1" height="1" fill={color} />
            <rect x="9" y="15" width="1" height="1" fill={color} />
            <rect x="10" y="15" width="1" height="1" fill={color} />
            <rect x="31" y="15" width="1" height="1" fill={secondColor} />
            <rect x="32" y="15" width="1" height="1" fill={secondColor} />
            <rect x="0" y="16" width="1" height="1" fill={color} />
            <rect x="1" y="16" width="1" height="1" fill={color} />
            <rect x="7" y="16" width="1" height="1" fill={secondColor} />
            <rect x="8" y="16" width="1" height="1" fill={color} />
            <rect x="13" y="16" width="1" height="1" fill={color} />
            <rect x="26" y="16" width="1" height="1" fill={color} />
            <rect x="31" y="16" width="1" height="1" fill={secondColor} />
            <rect x="32" y="16" width="1" height="1" fill={secondColor} />
            <rect x="2" y="17" width="1" height="1" fill={secondColor} />
            <rect x="3" y="17" width="1" height="1" fill={secondColor} />
            <rect x="4" y="17" width="1" height="1" fill={secondColor} />
            <rect x="5" y="17" width="1" height="1" fill={secondColor} />
            <rect x="6" y="17" width="1" height="1" fill={secondColor} />
            <rect x="7" y="17" width="1" height="1" fill={color} />
            <rect x="32" y="17" width="1" height="1" fill={secondColor} />
            <rect x="0" y="18" width="1" height="1" fill={color} />
            <rect x="3" y="18" width="1" height="1" fill={color} />
            <rect x="4" y="18" width="1" height="1" fill={color} />
            <rect x="5" y="18" width="1" height="1" fill={color} />
            <rect x="6" y="18" width="1" height="1" fill={color} />
            <rect x="7" y="18" width="1" height="1" fill={color} />
            <rect x="31" y="18" width="1" height="1" fill={secondColor} />
            <rect x="0" y="19" width="1" height="1" fill={color} />
            <rect x="1" y="19" width="1" height="1" fill={secondColor} />
            <rect x="3" y="19" width="1" height="1" fill={color} />
            <rect x="4" y="19" width="1" height="1" fill={color} />
            <rect x="5" y="19" width="1" height="1" fill={color} />
            <rect x="6" y="19" width="1" height="1" fill={color} />
            <rect x="7" y="19" width="1" height="1" fill={color} />
            <rect x="8" y="19" width="1" height="1" fill={color} />
            <rect x="31" y="19" width="1" height="1" fill={secondColor} />
            <rect x="0" y="20" width="1" height="1" fill={color} />
            <rect x="1" y="20" width="1" height="1" fill={secondColor} />
            <rect x="3" y="20" width="1" height="1" fill={color} />
            <rect x="7" y="20" width="1" height="1" fill={color} />
            <rect x="8" y="20" width="1" height="1" fill={color} />
            <rect x="32" y="20" width="1" height="1" fill={secondColor} />
            <rect x="0" y="21" width="1" height="1" fill={secondColor} />
            <rect x="2" y="21" width="1" height="1" fill={color} />
            <rect x="4" y="21" width="1" height="1" fill={color} />
            <rect x="5" y="21" width="1" height="1" fill={color} />
            <rect x="6" y="21" width="1" height="1" fill={color} />
            <rect x="9" y="21" width="1" height="1" fill={color} />
            <rect x="30" y="21" width="1" height="1" fill={secondColor} />
            <rect x="32" y="21" width="1" height="1" fill={secondColor} />
            <rect x="1" y="22" width="1" height="1" fill={color} />
            <rect x="2" y="22" width="1" height="1" fill={color} />
            <rect x="4" y="22" width="1" height="1" fill={color} />
            <rect x="6" y="22" width="1" height="1" fill={secondColor} />
            <rect x="7" y="22" width="1" height="1" fill={color} />
            <rect x="9" y="22" width="1" height="1" fill={color} />
            <rect x="30" y="22" width="1" height="1" fill={secondColor} />
            <rect x="0" y="23" width="1" height="1" fill={color} />
            <rect x="1" y="23" width="1" height="1" fill={color} />
            <rect x="2" y="23" width="1" height="1" fill={color} />
            <rect x="5" y="23" width="1" height="1" fill={secondColor} />
            <rect x="6" y="23" width="1" height="1" fill={secondColor} />
            <rect x="7" y="23" width="1" height="1" fill={color} />
            <rect x="9" y="23" width="1" height="1" fill={color} />
            <rect x="29" y="23" width="1" height="1" fill={secondColor} />
            <rect x="31" y="23" width="1" height="1" fill={secondColor} />
            <rect x="1" y="24" width="1" height="1" fill={color} />
            <rect x="2" y="24" width="1" height="1" fill={color} />
            <rect x="3" y="24" width="1" height="1" fill={secondColor} />
            <rect x="4" y="24" width="1" height="1" fill={secondColor} />
            <rect x="5" y="24" width="1" height="1" fill={color} />
            <rect x="6" y="24" width="1" height="1" fill={color} />
            <rect x="8" y="24" width="1" height="1" fill={secondColor} />
            <rect x="9" y="24" width="1" height="1" fill={color} />
            <rect x="30" y="24" width="1" height="1" fill={secondColor} />
            <rect x="2" y="25" width="1" height="1" fill={color} />
            <rect x="3" y="25" width="1" height="1" fill={color} />
            <rect x="4" y="25" width="1" height="1" fill={color} />
            <rect x="7" y="25" width="1" height="1" fill={secondColor} />
            <rect x="8" y="25" width="1" height="1" fill={color} />
            <rect x="9" y="25" width="1" height="1" fill={color} />
            <rect x="3" y="26" width="1" height="1" fill={color} />
            <rect x="4" y="26" width="1" height="1" fill={color} />
            <rect x="5" y="26" width="1" height="1" fill={color} />
            <rect x="6" y="26" width="1" height="1" fill={color} />
            <rect x="7" y="26" width="1" height="1" fill={color} />
            <rect x="8" y="26" width="1" height="1" fill={color} />
            <rect x="9" y="26" width="1" height="1" fill={color} />
        </svg>
    )
}

export default CurlersM
