import React from 'react'
import styles from '../../../Avatar.module.scss';
import { LooksColor } from '@/src/interface';

const DegradedM: React.FC<LooksColor> = ({ color, secondColor }) => {
    return (
        <svg version="1.1" viewBox='0 0 41 41' className={styles.colores} fill="currentColor" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">
            <rect x="9" y="0" width="1" height="1" fill={color} />
            <rect x="10" y="0" width="1" height="1" fill={color} />
            <rect x="11" y="0" width="1" height="1" fill={color} />
            <rect x="12" y="0" width="1" height="1" fill={color} />
            <rect x="13" y="0" width="1" height="1" fill={color} />
            <rect x="14" y="0" width="1" height="1" fill={color} />
            <rect x="20" y="0" width="1" height="1" fill={color} />
            <rect x="21" y="0" width="1" height="1" fill={color} />
            <rect x="22" y="0" width="1" height="1" fill={color} />
            <rect x="23" y="0" width="1" height="1" fill={color} />
            <rect x="24" y="0" width="1" height="1" fill={color} />
            <rect x="25" y="0" width="1" height="1" fill={color} />
            <rect x="26" y="0" width="1" height="1" fill={color} />
            <rect x="27" y="0" width="1" height="1" fill={color} />
            <rect x="8" y="1" width="1" height="1" fill={color} />
            <rect x="9" y="1" width="1" height="1" fill={color} />
            <rect x="10" y="1" width="1" height="1" fill={color} />
            <rect x="11" y="1" width="1" height="1" fill={color} />
            <rect x="15" y="1" width="1" height="1" fill={color} />
            <rect x="16" y="1" width="1" height="1" fill={color} />
            <rect x="17" y="1" width="1" height="1" fill={color} />
            <rect x="18" y="1" width="1" height="1" fill={color} />
            <rect x="19" y="1" width="1" height="1" fill={color} />
            <rect x="23" y="1" width="1" height="1" fill={color} />
            <rect x="24" y="1" width="1" height="1" fill={color} />
            <rect x="25" y="1" width="1" height="1" fill={color} />
            <rect x="26" y="1" width="1" height="1" fill={color} />
            <rect x="27" y="1" width="1" height="1" fill={color} />
            <rect x="28" y="1" width="1" height="1" fill={color} />
            <rect x="11" y="2" width="1" height="1" fill={color} />
            <rect x="12" y="2" width="1" height="1" fill={color} />
            <rect x="13" y="2" width="1" height="1" fill={color} />
            <rect x="17" y="2" width="1" height="1" fill={color} />
            <rect x="19" y="2" width="1" height="1" fill={color} />
            <rect x="20" y="2" width="1" height="1" fill={color} />
            <rect x="21" y="2" width="1" height="1" fill={color} />
            <rect x="25" y="2" width="1" height="1" fill={color} />
            <rect x="26" y="2" width="1" height="1" fill={color} />
            <rect x="27" y="2" width="1" height="1" fill={color} />
            <rect x="28" y="2" width="1" height="1" fill={color} />
            <rect x="29" y="2" width="1" height="1" fill={color} />
            <rect x="13" y="3" width="1" height="1" fill={color} />
            <rect x="14" y="3" width="1" height="1" fill={color} />
            <rect x="18" y="3" width="1" height="1" fill={color} />
            <rect x="19" y="3" width="1" height="1" fill={color} />
            <rect x="21" y="3" width="1" height="1" fill={color} />
            <rect x="22" y="3" width="1" height="1" fill={color} />
            <rect x="23" y="3" width="1" height="1" fill={color} />
            <rect x="24" y="3" width="1" height="1" fill={color} />
            <rect x="27" y="3" width="1" height="1" fill={color} />
            <rect x="28" y="3" width="1" height="1" fill={color} />
            <rect x="29" y="3" width="1" height="1" fill={color} />
            <rect x="30" y="3" width="1" height="1" fill={color} />
            <rect x="15" y="4" width="1" height="1" fill={color} />
            <rect x="16" y="4" width="1" height="1" fill={color} />
            <rect x="17" y="4" width="1" height="1" fill={color} />
            <rect x="20" y="4" width="1" height="1" fill={color} />
            <rect x="24" y="4" width="1" height="1" fill={color} />
            <rect x="25" y="4" width="1" height="1" fill={color} />
            <rect x="26" y="4" width="1" height="1" fill={color} />
            <rect x="29" y="4" width="1" height="1" fill={color} />
            <rect x="30" y="4" width="1" height="1" fill={color} />
            <rect x="31" y="4" width="1" height="1" fill={color} />
            <rect x="17" y="5" width="1" height="1" fill={color} />
            <rect x="18" y="5" width="1" height="1" fill={color} />
            <rect x="21" y="5" width="1" height="1" fill={color} />
            <rect x="22" y="5" width="1" height="1" fill={color} />
            <rect x="23" y="5" width="1" height="1" fill={color} />
            <rect x="24" y="5" width="1" height="1" fill={color} />
            <rect x="26" y="5" width="1" height="1" fill={color} />
            <rect x="27" y="5" width="1" height="1" fill={color} />
            <rect x="28" y="5" width="1" height="1" fill={color} />
            <rect x="31" y="5" width="1" height="1" fill={color} />
            <rect x="32" y="5" width="1" height="1" fill={color} />
            <rect x="18" y="6" width="1" height="1" fill={color} />
            <rect x="19" y="6" width="1" height="1" fill={color} />
            <rect x="22" y="6" width="1" height="1" fill={color} />
            <rect x="23" y="6" width="1" height="1" fill={color} />
            <rect x="24" y="6" width="1" height="1" fill={color} />
            <rect x="25" y="6" width="1" height="1" fill={color} />
            <rect x="28" y="6" width="1" height="1" fill={color} />
            <rect x="29" y="6" width="1" height="1" fill={color} />
            <rect x="32" y="6" width="1" height="1" fill={secondColor} />
            <rect x="19" y="7" width="1" height="1" fill={color} />
            <rect x="20" y="7" width="1" height="1" fill={color} />
            <rect x="23" y="7" width="1" height="1" fill={color} />
            <rect x="24" y="7" width="1" height="1" fill={color} />
            <rect x="25" y="7" width="1" height="1" fill={color} />
            <rect x="26" y="7" width="1" height="1" fill={color} />
            <rect x="29" y="7" width="1" height="1" fill={color} />
            <rect x="30" y="7" width="1" height="1" fill={color} />
            <rect x="32" y="7" width="1" height="1" fill={secondColor} />
            <rect x="33" y="7" width="1" height="1" fill={secondColor} />
            <rect x="20" y="8" width="1" height="1" fill={color} />
            <rect x="21" y="8" width="1" height="1" fill={color} />
            <rect x="24" y="8" width="1" height="1" fill={color} />
            <rect x="25" y="8" width="1" height="1" fill={color} />
            <rect x="26" y="8" width="1" height="1" fill={color} />
            <rect x="27" y="8" width="1" height="1" fill={color} />
            <rect x="28" y="8" width="1" height="1" fill={color} />
            <rect x="31" y="8" width="1" height="1" fill={secondColor} />
            <rect x="33" y="8" width="1" height="1" fill={secondColor} />
            <rect x="21" y="9" width="1" height="1" fill={color} />
            <rect x="22" y="9" width="1" height="1" fill={color} />
            <rect x="25" y="9" width="1" height="1" fill={color} />
            <rect x="26" y="9" width="1" height="1" fill={color} />
            <rect x="27" y="9" width="1" height="1" fill={color} />
            <rect x="28" y="9" width="1" height="1" fill={color} />
            <rect x="29" y="9" width="1" height="1" fill={color} />
            <rect x="31" y="9" width="1" height="1" fill={secondColor} />
            <rect x="33" y="9" width="1" height="1" fill={secondColor} />
            <rect x="21" y="10" width="1" height="1" fill={color} />
            <rect x="22" y="10" width="1" height="1" fill={color} />
            <rect x="23" y="10" width="1" height="1" fill={color} />
            <rect x="26" y="10" width="1" height="1" fill={color} />
            <rect x="27" y="10" width="1" height="1" fill={color} />
            <rect x="28" y="10" width="1" height="1" fill={color} />
            <rect x="29" y="10" width="1" height="1" fill={color} />
            <rect x="31" y="10" width="1" height="1" fill={secondColor} />
            <rect x="32" y="10" width="1" height="1" fill={secondColor} />
            <rect x="34" y="10" width="1" height="1" fill={secondColor} />
            <rect x="22" y="11" width="1" height="1" fill={color} />
            <rect x="23" y="11" width="1" height="1" fill={color} />
            <rect x="26" y="11" width="1" height="1" fill={color} />
            <rect x="27" y="11" width="1" height="1" fill={color} />
            <rect x="28" y="11" width="1" height="1" fill={color} />
            <rect x="29" y="11" width="1" height="1" fill={color} />
            <rect x="32" y="11" width="1" height="1" fill={secondColor} />
            <rect x="33" y="11" width="1" height="1" fill={secondColor} />
            <rect x="34" y="11" width="1" height="1" fill={secondColor} />
            <rect x="35" y="11" width="1" height="1" fill={secondColor} />
            <rect x="22" y="12" width="1" height="1" fill={color} />
            <rect x="23" y="12" width="1" height="1" fill={color} />
            <rect x="27" y="12" width="1" height="1" fill={color} />
            <rect x="28" y="12" width="1" height="1" fill={color} />
            <rect x="29" y="12" width="1" height="1" fill={color} />
            <rect x="30" y="12" width="1" height="1" fill={color} />
            <rect x="32" y="12" width="1" height="1" fill={secondColor} />
            <rect x="33" y="12" width="1" height="1" fill={secondColor} />
            <rect x="34" y="12" width="1" height="1" fill={secondColor} />
            <rect x="35" y="12" width="1" height="1" fill={secondColor} />
            <rect x="23" y="13" width="1" height="1" fill={color} />
            <rect x="24" y="13" width="1" height="1" fill={color} />
            <rect x="28" y="13" width="1" height="1" fill={color} />
            <rect x="29" y="13" width="1" height="1" fill={color} />
            <rect x="30" y="13" width="1" height="1" fill={color} />
            <rect x="31" y="13" width="1" height="1" fill={color} />
            <rect x="33" y="13" width="1" height="1" fill={secondColor} />
            <rect x="34" y="13" width="1" height="1" fill={secondColor} />
            <rect x="24" y="14" width="1" height="1" fill={color} />
            <rect x="29" y="14" width="1" height="1" fill={color} />
            <rect x="30" y="14" width="1" height="1" fill={color} />
            <rect x="31" y="14" width="1" height="1" fill={color} />
            <rect x="33" y="14" width="1" height="1" fill={secondColor} />
            <rect x="34" y="14" width="1" height="1" fill={secondColor} />
            <rect x="24" y="15" width="1" height="1" fill={color} />
            <rect x="29" y="15" width="1" height="1" fill={color} />
            <rect x="30" y="15" width="1" height="1" fill={color} />
            <rect x="31" y="15" width="1" height="1" fill={color} />
            <rect x="32" y="15" width="1" height="1" fill={secondColor} />
            <rect x="33" y="15" width="1" height="1" fill={secondColor} />
            <rect x="35" y="15" width="1" height="1" fill={secondColor} />
            <rect x="13" y="16" width="1" height="1" fill={color} />
            <rect x="26" y="16" width="1" height="1" fill={color} />
            <rect x="30" y="16" width="1" height="1" fill={color} />
            <rect x="31" y="16" width="1" height="1" fill={color} />
            <rect x="32" y="16" width="1" height="1" fill={color} />
            <rect x="33" y="16" width="1" height="1" fill={secondColor} />
            <rect x="35" y="16" width="1" height="1" fill={secondColor} />
            <rect x="30" y="17" width="1" height="1" fill={color} />
            <rect x="31" y="17" width="1" height="1" fill={color} />
            <rect x="32" y="17" width="1" height="1" fill={secondColor} />
            <rect x="34" y="17" width="1" height="1" fill={secondColor} />
            <rect x="35" y="17" width="1" height="1" fill={secondColor} />
            <rect x="31" y="18" width="1" height="1" fill={color} />
            <rect x="32" y="18" width="1" height="1" fill={secondColor} />
            <rect x="34" y="18" width="1" height="1" fill={secondColor} />
            <rect x="31" y="19" width="1" height="1" fill={color} />
            <rect x="32" y="19" width="1" height="1" fill={secondColor} />
            <rect x="33" y="19" width="1" height="1" fill={secondColor} />
            <rect x="31" y="20" width="1" height="1" fill={color} />
            <rect x="32" y="20" width="1" height="1" fill={secondColor} />
            <rect x="33" y="20" width="1" height="1" fill={secondColor} />
            <rect x="34" y="20" width="1" height="1" fill={secondColor} />
            <rect x="30" y="21" width="1" height="1" fill={color} />
            <rect x="31" y="21" width="1" height="1" fill={color} />
            <rect x="32" y="21" width="1" height="1" fill={secondColor} />
            <rect x="33" y="21" width="1" height="1" fill={secondColor} />
            <rect x="30" y="22" width="1" height="1" fill={color} />
            <rect x="31" y="22" width="1" height="1" fill={color} />
            <rect x="32" y="22" width="1" height="1" fill={secondColor} />
            <rect x="34" y="22" width="1" height="1" fill={secondColor} />
            <rect x="29" y="23" width="1" height="1" fill={color} />
            <rect x="30" y="23" width="1" height="1" fill={color} />
            <rect x="31" y="23" width="1" height="1" fill={secondColor} />
            <rect x="32" y="23" width="1" height="1" fill={secondColor} />
            <rect x="33" y="23" width="1" height="1" fill={secondColor} />
            <rect x="34" y="23" width="1" height="1" fill={secondColor} />
            <rect x="29" y="24" width="1" height="1" fill={color} />
            <rect x="30" y="24" width="1" height="1" fill={color} />
            <rect x="31" y="24" width="1" height="1" fill={secondColor} />
            <rect x="33" y="24" width="1" height="1" fill={secondColor} />
            <rect x="29" y="25" width="1" height="1" fill={color} />
            <rect x="30" y="25" width="1" height="1" fill={secondColor} />
            <rect x="31" y="25" width="1" height="1" fill={secondColor} />
            <rect x="33" y="25" width="1" height="1" fill={secondColor} />
            <rect x="29" y="26" width="1" height="1" fill={color} />
            <rect x="30" y="26" width="1" height="1" fill={secondColor} />
            <rect x="32" y="26" width="1" height="1" fill={secondColor} />
            <rect x="29" y="27" width="1" height="1" fill={color} />
            <rect x="29" y="28" width="1" height="1" fill={color} />
            <rect x="30" y="29" width="1" height="1" fill={color} />
        </svg>
    )
}

export default DegradedM