import React from 'react'
import styles from '../../../Sprite.module.scss';
import {spriteHair} from '@/src/interface/avatar'

const Vertical: React.FC<spriteHair> = ({position, colorSecond, colorPrincipal}) => {
    return (
        <svg version="1.1" className={styles.sprite} viewBox={`${position.x} ${position.y} 128 32`} fill="currentColor"
             xmlns="http://www.w3.org/2000/svg" shapeRendering="crispEdges">
            <rect x="11" y="3" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="3" width="1" height="1" fill={colorPrincipal}/>
            <rect x="19" y="3" width="1" height="1" fill="#F0E8F2"/>
            <rect x="75" y="3" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="3" width="1" height="1" fill={colorPrincipal}/>
            <rect x="83" y="3" width="1" height="1" fill="#F0E8F2"/>
            <rect x="11" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="19" y="4" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="4" width="1" height="1" fill="#F0E8F2"/>
            <rect x="43" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="51" y="4" width="1" height="1" fill="#F0E8F2"/>
            <rect x="75" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="83" y="4" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="4" width="1" height="1" fill="#F0E8F2"/>
            <rect x="107" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="4" width="1" height="1" fill={colorPrincipal}/>
            <rect x="115" y="4" width="1" height="1" fill="#F0E8F2"/>
            <rect x="10" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="19" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="43" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="51" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="74" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="83" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="107" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="5" width="1" height="1" fill={colorPrincipal}/>
            <rect x="115" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="5" width="1" height="1" fill="#F0E8F2"/>
            <rect x="10" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="19" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="42" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="51" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="74" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="83" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="106" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="6" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="115" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="6" width="1" height="1" fill="#F0E8F2"/>
            <rect x="9" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="10" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="19" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="42" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="51" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="73" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="74" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="83" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="106" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="7" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="115" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="7" width="1" height="1" fill="#F0E8F2"/>
            <rect x="8" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="9" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="10" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="21" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="41" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="42" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="51" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="72" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="73" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="74" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="85" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="105" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="106" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="8" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="115" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="8" width="1" height="1" fill="#F0E8F2"/>
            <rect x="9" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="10" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="9" width="1" height="1" fill="#D4DF99"/>
            <rect x="16" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="9" width="1" height="1" fill="#F0E8F2"/>
            <rect x="19" y="9" width="1" height="1" fill="#D4DF99"/>
            <rect x="40" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="41" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="42" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="9" width="1" height="1" fill="#F0E8F2"/>
            <rect x="53" y="9" width="1" height="1" fill="#F0E8F2"/>
            <rect x="73" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="74" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="9" width="1" height="1" fill="#D4DF99"/>
            <rect x="80" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="9" width="1" height="1" fill="#F0E8F2"/>
            <rect x="83" y="9" width="1" height="1" fill="#D4DF99"/>
            <rect x="104" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="105" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="106" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="9" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="9" width="1" height="1" fill="#F0E8F2"/>
            <rect x="117" y="9" width="1" height="1" fill="#F0E8F2"/>
            <rect x="10" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="19" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="41" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="42" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="10" width="1" height="1" fill="#D4DF99"/>
            <rect x="48" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="51" y="10" width="1" height="1" fill="#D4DF99"/>
            <rect x="74" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="83" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="105" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="106" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="10" width="1" height="1" fill="#D4DF99"/>
            <rect x="112" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="10" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="10" width="1" height="1" fill="#F0E8F2"/>
            <rect x="115" y="10" width="1" height="1" fill="#D4DF99"/>
            <rect x="10" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="19" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="42" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="51" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="74" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="83" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="106" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="11" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="115" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="11" width="1" height="1" fill="#F0E8F2"/>
            <rect x="9" y="12" width="1" height="1" fill={colorSecond}/>
            <rect x="10" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="11" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="12" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="19" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="20" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="21" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="42" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="51" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="73" y="12" width="1" height="1" fill={colorSecond}/>
            <rect x="74" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="75" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="76" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="77" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="83" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="84" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="85" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="106" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="12" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="115" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="12" width="1" height="1" fill="#F0E8F2"/>
            <rect x="10" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="11" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="12" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="13" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="14" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="15" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="18" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="19" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="41" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="42" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="43" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="51" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="52" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="53" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="74" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="75" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="76" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="77" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="79" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="80" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="83" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="105" y="13" width="1" height="1" fill={colorSecond}/>
            <rect x="106" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="107" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="108" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="109" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="13" width="1" height="1" fill={colorPrincipal}/>
            <rect x="115" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="116" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="117" y="13" width="1" height="1" fill="#F0E8F2"/>
            <rect x="42" y="14" width="1" height="1" fill={colorSecond}/>
            <rect x="43" y="14" width="1" height="1" fill={colorSecond}/>
            <rect x="44" y="14" width="1" height="1" fill={colorSecond}/>
            <rect x="45" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="46" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="47" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="51" y="14" width="1" height="1" fill="#F0E8F2"/>
            <rect x="106" y="14" width="1" height="1" fill={colorSecond}/>
            <rect x="107" y="14" width="1" height="1" fill={colorSecond}/>
            <rect x="108" y="14" width="1" height="1" fill={colorSecond}/>
            <rect x="109" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="114" y="14" width="1" height="1" fill={colorPrincipal}/>
            <rect x="115" y="14" width="1" height="1" fill="#F0E8F2"/>
            <rect x="16" y="15" width="1" height="1" fill={colorSecond}/>
            <rect x="80" y="15" width="1" height="1" fill={colorSecond}/>
            <rect x="16" y="16" width="1" height="1" fill={colorPrincipal}/>
            <rect x="48" y="16" width="1" height="1" fill={colorSecond}/>
            <rect x="80" y="16" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="16" width="1" height="1" fill={colorSecond}/>
            <rect x="48" y="17" width="1" height="1" fill={colorPrincipal}/>
            <rect x="112" y="17" width="1" height="1" fill={colorPrincipal}/>
            <rect x="16" y="28" width="1" height="1" fill={colorSecond}/>
            <rect x="17" y="28" width="1" height="1" fill={colorSecond}/>
            <rect x="78" y="28" width="1" height="1" fill={colorSecond}/>
            <rect x="13" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="16" y="29" width="1" height="1" fill={colorPrincipal}/>
            <rect x="17" y="29" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="49" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="50" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="77" y="29" width="1" height="1" fill={colorPrincipal}/>
            <rect x="78" y="29" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="82" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="111" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="113" y="29" width="1" height="1" fill={colorSecond}/>
            <rect x="12" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="13" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="44" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="45" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="49" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="50" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="81" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="82" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="110" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="111" y="30" width="1" height="1" fill={colorPrincipal}/>
            <rect x="113" y="30" width="1" height="1" fill={colorPrincipal}/>
        </svg>
    )
}

export default Vertical